LukeMathWalker/tracing-actix-web

- src/lib.rs
Concept to allow extracting the request ID, that is used in the logs and use it in request handlers.
With this you should be able to do something like this:
```rust
#[get("/")]
fn index(request_id: RequestId) -> String {
format!("{}", request_id.uuid())
}
```
Some things, I'm not quite happy about, that should be discussed:
Closes #2
> Make request ID extractable in request handlers

- src/lib.rs
Closes #5.
Nothing complex here, just adding the method to the span. (: 
As a bonus, the method is marked as required by [OTEL conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md), so it's even greater to have it here.
> Add HTTP method to span fields

- src/request_id.rs
So it can be used in `tracing::instrument`.
> Implement Debug for RequestId

- Cargo.toml
- src/middleware.rs
I added this to my project while reading through Zero to Production in Rust and found it pulled in a few `futures` crates that I had so far managed to avoid pulling in. Since the standard library has the `Ready` type now, which was the only thing imported from futures, I've just removed the dependency entirely rather than swapping the dependency to `futures-util` instead. This is fine since the actix-web 4.0.0-beta.9 bumped MSRV to 1.51, and Ready was added in 1.48.
> Don't pull in unneeded dependency on futures

- src/middleware.rs
I noticed that some logging in one of my middlwares wasn't getting wrapped in the root span, and I determined it was because the function call that produces the middleware future is not itself wrapped in the root span
> Allow root_span to wrap the full middlware chain, not just the output future

- Cargo.toml
- src/middleware.rs
This introduces a new `TracingResponse` Future and a new `StreamSpan` MessageBody. Now, each poll of the message body happens inside the root span, meaning that default and custom body streams will be properly wrapped. Since the span is held in the body, it will remain open until the body itself is dropped.
This also adds a new dependency on `pin_project` which introduces unsafe code via it's `pin_project` macro. The alternative would be to `Box::pin` the body and the inner service's future, which may be preferable. 
closes https://github.com/LukeMathWalker/tracing-actix-web/issues/39
Just a note that if any consumers of this crate were relying on timings provided previously, this will make all requests that produce a body seem to take longer, since the span is held open longer
> Hold root span across polls in streamed body

- README.md
For whatever reason, it seems like docs.rs no longer likes dashes in the second instance of the crate name in the URL. This may be a docs.rs regression, but in the meantime, I figured it would be helpful to have working links in the readme.
> Fix docs.rs links

- Cargo.toml
- README.md
- examples/custom-root-span/Cargo.toml
- examples/opentelemetry/Cargo.toml
- src/lib.rs
Feels weird to pin the dep in a library. I feel that it should be delegated to the end consumer.
> Updated actix-web dependency to `4.0.0-beta.18`

- .github/workflows/general.yml
- Cargo.toml
- README.md
- examples/custom-root-span/Cargo.toml
- examples/opentelemetry/Cargo.toml
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
there's no longer a `.to_hex()` method on `TraceId`, but I pulled the format string it used from 0.16 directly into the `otel.rs` file
> Add support for opentelemetry 0.17, actix-web rc.2

- src/root_span_macro.rs
Add the otel.name field to the root span with the `HTTP {method} {path}` format, following the [otel guidelines] on span names (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md).
It overrides the `HTTP Request` span name set for the `tracing` span when exporting opentelemetry data and is a lot more readable in UIs like Jaeger, for example with the provided demo:
Questions:
- I'm not sure if we should go with `HTTP {method} {path}` or just `{method} {path}`, but if the app also receives other types of requests it might be better to be explicit.
- Is `format!` the best way way to create the string there ?
> Add otel.name field to the root span

- .github/workflows/general.yml
- Cargo.toml
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
closes https://github.com/LukeMathWalker/tracing-actix-web/issues/88
> Support opentelemetry 0.18

- src/lib.rs
- src/root_span_builder.rs
- src/root_span_macro.rs
*Issue #, if available:* Resolves #92
This PR bounds the type parameter of `RootSpanBuilder::on_request_end` with `actix_web::body::MessageBody`.
This doesn't directly break any use-cases, since this method is always used in cases where this bound holds (see description of #92). However, this does introduce a **breaking change** in the public API, and thus will involve bumping the minor version (since the current version is 0.x).
> Bound type-param of RootSpanBuilder::on_request_end

- examples/custom-root-span/src/main.rs
This fixes the custom example `examples/custom-root-span`, which was broken with PR #93.
> Fixed example for custom root span builder

- README.md
I know, I know, I should've caught this too 😅. Hopefully this is the last one.
This fixes the code in the README, which was broken with PR #93.
> Fixed custom root span builder code in README

- src/lib.rs
The version used for `tracing-actix-web` in the documentation in `src/lib.rs` was set to 0.6, but the code only works with 0.7.
> Fixed version number in lib.rs

- src/lib.rs
In order to create a "build_app" function, it needs to see `StreamSpan` like so:
```rust
pub fn build_app() -> App<
impl ServiceFactory<
ServiceRequest,
Config = (),
Response = ServiceResponse<tracing_actix_web::StreamSpan<BoxBody>>,
Error = actix_web::Error,
InitError = (),
>,
> { ... }
```
> Expose StreamSpan

- Cargo.toml
- examples/request-id-response-header/Cargo.toml
- examples/request-id-response-header/README.md
- examples/request-id-response-header/src/main.rs
This adds an example showing how one can set the request id as a response header as discussed in ##107
> Add request-id header example

- .github/workflows/general.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/request_id.rs
Linked Issue: #115
---
Description:
feature flag `uuid_v7` is introduced which inturn enables `v7` feature flag in the `uuid` dependency Support documentation is added in `README.md`, `src/lib.rs` and `src/request_id.rs`
This feature only works if this crate or any crate dependent on this crate has enabled the compile time configuration flag provided to the rust compiler. `RUSTFLAGS="--cfg uuid_unstable"`.
---
> add support for UUID v7 in `RequestId`

- Cargo.toml
- README.md
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
Adds support for OpenTelemetry 0.21. Nothing particularly interesting. While here, getting rid of the Fibonacci-exploding number of compile guards and use a single const-evaluated expression.
> Add support for OpenTelemetry 0.21

- .github/workflows/general.yml
- Cargo.toml
- README.md
- examples/custom-root-span/Cargo.toml
- examples/opentelemetry/Cargo.toml
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
Support Open Telemetry 0.22
It's a draft, waiting for the `tracing-opentelemetry 0.23` to be available.
> Support otel 0.22

- .github/workflows/general.yml
- README.md
- src/lib.rs
- src/request_id.rs
This PR removes the requirement that `RUSTFLAGS="--cfg uuid_unstable"` be provided to use the `uuid_v7` feature flag, and thus the `v7` feature flag from the `uuid` crate.
The `uuid` crate stabilized support for UUID v6-v8 in uuid-rs/uuid#718, which was included in the `1.6.0` release of the `uuid` crate. Since `tracing-actix-web` pulls the `uuid` crate using only the major version (`1`) and does not include the minor version, I believe it is safe to remove the `--cfg uuid_unstable` requirement.
Essentially, I just went through the changes done in #116 and removed some lines which were no longer applicable.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Remove `--cfg uuid_unstable` requirement for `uuid_v7` feature

- .github/workflows/general.yml
- Cargo.toml
- README.md
- examples/opentelemetry/Cargo.toml
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
Support Open Telemetry 0.23
It's a draft, waiting for the `tracing-opentelemetry 0.24` to be available.
> Support otel 0.23

- .github/workflows/general.yml
- Cargo.toml
- README.md
- examples/custom-root-span/Cargo.toml
- examples/custom-root-span/src/main.rs
- examples/opentelemetry/Cargo.toml
- examples/opentelemetry/src/main.rs
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
`opentelemetry-jaeger` is deprecated and reached eol. ([More](https://crates.io/crates/opentelemetry-jaeger) [info](https://opentelemetry.io/blog/2022/jaeger-native-otlp/))
> Support otel 0.24

- src/root_span_macro.rs
see: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#name
Hey,
I am not sure if the convention has changed recently or if this "HTTP" at the beginning of the name had a purpose, but this is breaking some compatibilities with other tools. Kindly let me know what you think please 😃 
Thank you!
> fix: follow latest OTEL semantic conventions for the span name

- examples/opentelemetry/README.md
Add missing jaeger exposed port 4317
Without this port exposed, the exporter is not able to connect to the endpoint.
> Update opentelemetry example documentation

- Cargo.toml
- README.md
- examples/custom-root-span/Cargo.toml
- examples/custom-root-span/src/main.rs
- examples/opentelemetry/Cargo.toml
- examples/opentelemetry/src/main.rs
- src/lib.rs
- src/otel.rs
- src/root_span_macro.rs
Closes https://github.com/LukeMathWalker/tracing-actix-web/issues/138
> Support opentelemetry 0.28
